name: Delete-workflow-runs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 1 * *
    # UTC 时区，比北京时间慢 8 个小时，示例为 “北京时间每天0点”

env:

  TZ: Asia/Shanghai
  DEL_FLOW: true
  DEL_FLOW_ACT: Mattraks/delete-workflow-runs
  DEL_FLOW_ACT_VER: v2.0.3
  # 不要带 http:// 或者 https:// 等地址前缀

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
                
      - name: Delete workflow runs
        if: env.DEL_FLOW == 'true'
        uses: env.DEL_FLOW_ACT@env.DEL_FLOW_ACT_VER
        with:
          retain_days: 30
          keep_minimum_runs: 15
