name: Delete workflow runs

on:
  workflow_dispatch:
  #schedule:
    #- cron: '00 16 * * *'

env:
  TZ: Asia/Shanghai
  DEL_FLOW: true
  USE_SSH: true
  
jobs:
  delete:
    runs-on: ubuntu-latest
    if: github.event.sender.id == '54447830' || github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - uses: actions/checkout@v2
        with:
            persist-credentials: false
       
      - name: Initial environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
          git config --global user.name 'GitHub Actions' 
          git config --global user.email 'noreply@github.com'
        
      - name: Delete workflow runs
        if: env.DEL_FLOW == 'true'
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:          
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
