name: build ztncui
on:
  workflow_dispatch:
  #schedule:
   # - cron: 35 21 * * 4

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install build dependencies
        run: |
          df -h
          # git clone 源代码至 ztncui 目录
          git clone https://github.com/key-networks/ztncui-aio.git ztncui

      - name: login docker
        run: |
          # 打开 ztncui 目录
          cd ztncui
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          # 启用 buildx 插件
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap
          docker buildx ls

      - name: Build Docker gimls
        run: |
          cd ztncui
          docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/gimls --platform=linux/amd64,linux/arm,linux/arm64 . --push

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 30
          keep_minimum_runs: 10
          
          
