# Ausaci CopyRight

name: Upload2Armbian_Buster

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

#  schedule:
#    - cron: 30 23 * * *
#  release:
#    types: published
#  watch:
#    types: started

env:
  UPLOAD_FILES: false
  TZ: Asia/Shanghai
  TAG_BRANCH: main
  TAG_NAME: TAG_TEST
  RELEASE_NAME: Armbian_Buster

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      
    - name: Checkout
      uses: actions/checkout@master

    - name: Download Files
      id: download
      run: |
        sudo mkdir -p /workdir/downloads
        sudo chmod 777 /workdir/downloads
        cd /workdir/downloads
        sudo wget $(curl -s https://api.github.com/repos/HoldOnBro/Actions-OpenWrt/releases/39511025 | grep browser_download_url | cut -d '"' -f 4)
        echo "::set-output name=status::success"
        
    - name: Organize Files
      id: organize
      if: steps.download.outputs.status == 'success' && !cancelled()
      run: |
        cd /workdir/downloads
        echo "FILES=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload Files
      uses: actions/upload-artifact@master
      if: env.UPLOAD_FILES == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.RELEASE_NAME }}
        path: ${{ env.FILES }}

    - name: Create release
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        commit: ${{ env.TAG_BRANCH }}
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
         Upload Armbian Buster from [Here](https://github.com/HoldOnBro/Actions-OpenWrt/releases/tag/Files4Compile)
        artifacts: ${{ env.FILES }}/*
